// ===== Quiz Data =====

export const QUIZ_CATEGORIES = [
  {
    id: 'fruits',
    title: 'Fruits',
    icon: '🍎',
    color: 'sorting',
    desc: 'Name fruits from their picture! A juicy challenge for little learners.',
    ageRange: '3–8'
  },
  {
    id: 'flowers',
    title: 'Flowers',
    icon: '🌸',
    color: 'patterns',
    desc: 'Identify beautiful flowers from around the world!',
    ageRange: '4–9'
  },
  {
    id: 'shapes',
    title: 'Shapes',
    icon: '⭐',
    color: 'word',
    desc: 'Match shapes to their names — from circles to hexagons!',
    ageRange: '3–7'
  },
  {
    id: 'animals',
    title: 'Animals',
    icon: '🦁',
    color: 'memory',
    desc: 'Can you name all these wonderful animals? Let\'s find out!',
    ageRange: '3–8'
  },
  {
    id: 'colors',
    title: 'Colors',
    icon: '🎨',
    color: 'patterns',
    desc: 'Match colors to cute objects and name them correctly!',
    ageRange: '3–6'
  },
  {
    id: 'vehicles',
    title: 'Vehicles',
    icon: '🚗',
    color: 'counting',
    desc: 'Identify different vehicles and modes of transport!',
    ageRange: '3–8'
  },
  {
    id: 'birds',
    title: 'Birds',
    icon: '🐦',
    color: 'sky',
    desc: 'Spot and name amazing birds — from tiny chicks to proud peacocks!',
    ageRange: '3–8'
  },
  {
    id: 'vegetables',
    title: 'Vegetables',
    icon: '🥕',
    color: 'garden',
    desc: 'Name healthy veggies — from crunchy carrots to leafy greens!',
    ageRange: '3–9'
  },
  {
    id: 'insects',
    title: 'Insects',
    icon: '🐞',
    color: 'garden',
    desc: 'Identify buzzy bugs and creepy-crawlies!',
    ageRange: '3–8'
  },
  {
    id: 'space',
    title: 'Space',
    icon: '🚀',
    color: 'sky',
    desc: 'Explore rockets, planets, and stars far away!',
    ageRange: '3–9'
  },
  {
    id: 'dinosaurs',
    title: 'Dinosaur Quiz',
    icon: '🦖',
    color: 'sorting',
    desc: 'Rawr! Name and spot these prehistoric giant creatures!',
    ageRange: '4–9'
  },
  {
    id: 'sea-creatures',
    title: 'Sea Creatures',
    icon: '🐙',
    color: 'sky',
    desc: 'Dive deep under the sea and find sharks, crabs, and whales!',
    ageRange: '3–8'
  },
  {
    id: 'world-wonders',
    title: 'World Wonders',
    icon: '🏛️',
    color: 'sorting',
    desc: 'Journey across continents to test your knowledge of famous landmarks!',
    ageRange: '5–10'
  },
  {
    id: 'inventions',
    title: 'Inventions & Discoveries',
    icon: '💡',
    color: 'counting',
    desc: 'Who invented the light bulb or telephone? Test your invention knowledge!',
    ageRange: '5–10'
  },
  {
    id: 'musical-instruments',
    title: 'Musical Instruments',
    icon: '🎵',
    color: 'word',
    desc: 'From drums to pianos, can you name all these instruments?',
    ageRange: '3–9'
  },
  {
    id: 'good-habits',
    title: 'Good Habits & Hygiene',
    icon: '🧼',
    color: 'counting',
    desc: 'Learn daily good habits from brushing teeth to washing hands!',
    ageRange: '3–8'
  }
];

export const QUIZ_DATA = {
  fruits: {
    title: 'Fruit Quiz',
    completionEmoji: '🍎',
    completionMessage: 'You know your fruits so well! 🍉',
    questions: [
      { id: 'apple', emoji: '🍎', question: 'What fruit is this?', answer: 'Apple', options: ['Tomato', 'Apple', 'Cherry', 'Strawberry'] },
      { id: 'banana', emoji: '🍌', question: 'What fruit is this?', answer: 'Banana', options: ['Mango', 'Corn', 'Banana', 'Lemon'] },
      { id: 'grapes', emoji: '🍇', question: 'What fruit is this?', answer: 'Grapes', options: ['Blueberry', 'Grapes', 'Cherry', 'Plum'] },
      { id: 'strawberry', emoji: '🍓', question: 'What fruit is this?', answer: 'Strawberry', options: ['Strawberry', 'Raspberry', 'Cherry', 'Apple'] },
      { id: 'orange', emoji: '🍊', question: 'What fruit is this?', answer: 'Orange', options: ['Peach', 'Apricot', 'Orange', 'Mango'] },
      { id: 'pineapple', emoji: '🍍', question: 'What fruit is this?', answer: 'Pineapple', options: ['Cactus', 'Coconut', 'Artichoke', 'Pineapple'] },
      { id: 'watermelon', emoji: '🍉', question: 'What fruit is this?', answer: 'Watermelon', options: ['Melon', 'Watermelon', 'Cucumber', 'Papaya'] },
      { id: 'mango', emoji: '🥭', question: 'What fruit is this?', answer: 'Mango', options: ['Papaya', 'Peach', 'Mango', 'Guava'] },
      { id: 'cherry', emoji: '🍒', question: 'What fruit is this?', answer: 'Cherry', options: ['Cherry', 'Strawberry', 'Cranberry', 'Plum'] },
      { id: 'kiwi', emoji: '🥝', question: 'What fruit is this?', answer: 'Kiwi', options: ['Avocado', 'Lime', 'Kiwi', 'Fig'] },
      { id: 'pear', emoji: '🍐', question: 'Which fruit is shaped like a little bell?', answer: 'Pear', options: ['Pear', 'Apple', 'Peach', 'Squash'] },
      { id: 'lemon', emoji: '🍋', question: 'Which sour yellow fruit is used to make lemonade?', answer: 'Lemon', options: ['Lemon', 'Lime', 'Banana', 'Corn'] },
      { id: 'peach', emoji: '🍑', question: 'Which soft, fuzzy fruit has a stone inside?', answer: 'Peach', options: ['Peach', 'Plum', 'Apricot', 'Tomato'] },
      { id: 'blueberry', emoji: '🫐', question: 'Which tiny blue fruit grows in clusters?', answer: 'Blueberry', options: ['Blueberry', 'Grape', 'Cherry', 'Plum'] },
      { id: 'coconut', emoji: '🥥', question: 'Which fruit has a hairy shell and sweet white inside?', answer: 'Coconut', options: ['Coconut', 'Walnut', 'Melon', 'Peach'] },
      { id: 'melon', emoji: '🍈', question: 'Which big round fruit is sweet and green inside?', answer: 'Melon', options: ['Melon', 'Watermelon', 'Pumpkin', 'Apple'] },
      { id: 'greenapple', emoji: '🍏', question: 'Which apple is green and tangy?', answer: 'Green Apple', options: ['Green Apple', 'Lime', 'Pear', 'Kiwi'] },
      { id: 'fruitsalad', emoji: '🥗', question: 'What do we call a bowl of mixed chopped fruits?', answer: 'Fruit Salad', options: ['Fruit Salad', 'Salad', 'Soup', 'Stew'] },
      { id: 'juice', emoji: '🧃', question: 'What drink is made by squeezing fruits?', answer: 'Juice', options: ['Juice', 'Water', 'Milk', 'Soda'] },
      { id: 'jam', emoji: '🍯', question: 'What sweet spread is made by cooking fruit with sugar?', answer: 'Jam', options: ['Jam', 'Honey', 'Butter', 'Sauce'] }
    ]
  },
  flowers: {
    title: 'Flower Quiz',
    completionEmoji: '🌸',
    completionMessage: 'You have a green thumb! 🌻',
    questions: [
      { id: 'rose', emoji: '🌹', question: 'Which flower is this?', answer: 'Rose', options: ['Poppy', 'Rose', 'Tulip', 'Peony'] },
      { id: 'sunflower', emoji: '🌻', question: 'Which flower is this?', answer: 'Sunflower', options: ['Daisy', 'Marigold', 'Sunflower', 'Dandelion'] },
      { id: 'tulip', emoji: '🌷', question: 'Which flower is this?', answer: 'Tulip', options: ['Lily', 'Orchid', 'Crocus', 'Tulip'] },
      { id: 'lotus', emoji: '🪷', question: 'Which flower is this?', answer: 'Lotus', options: ['Lotus', 'Lily', 'Water Lily', 'Jasmine'] },
      { id: 'hibiscus', emoji: '🌺', question: 'Which flower is this?', answer: 'Hibiscus', options: ['Bougainvillea', 'Hibiscus', 'Dahlia', 'Petunia'] },
      { id: 'blossom', emoji: '🌸', question: 'Which flower is this?', answer: 'Cherry Blossom', options: ['Jasmine', 'Magnolia', 'Cherry Blossom', 'Almond Blossom'] },
      { id: 'bouquet', emoji: '💐', question: 'What do we call a bunch of flowers?', answer: 'Bouquet', options: ['Wreath', 'Garland', 'Bouquet', 'Bunch'] },
      { id: 'daisy', emoji: '🌼', question: 'Which flower is this?', answer: 'Daisy', options: ['Chamomile', 'Daisy', 'Aster', 'Marigold'] },
      { id: 'herb', emoji: '🌿', question: 'What do we call sweet-smelling plants used in cooking?', answer: 'Herbs', options: ['Spices', 'Herbs', 'Weeds', 'Ferns'] },
      { id: 'seed', emoji: '🌱', question: 'How does a flower start its life?', answer: 'As a Seed', options: ['As a Leaf', 'As a Fruit', 'As a Stem', 'As a Seed'] },
      { id: 'clover', emoji: '🍀', question: 'Which small plant has three lucky leaves?', answer: 'Clover', options: ['Clover', 'Grass', 'Fern', 'Moss'] },
      { id: 'wheat', emoji: '🌾', question: 'Which golden plant do we grind into flour for bread?', answer: 'Wheat', options: ['Wheat', 'Rice', 'Corn', 'Grass'] },
      { id: 'violet', emoji: '💜', question: 'Which tiny purple flower is known for its sweet smell?', answer: 'Violet', options: ['Violet', 'Rose', 'Tulip', 'Daisy'] },
      { id: 'leaf', emoji: '🍃', question: 'What green part of a plant catches sunlight?', answer: 'Leaf', options: ['Leaf', 'Petal', 'Root', 'Stem'] },
      { id: 'nectar', emoji: '🍯', question: 'What sweet liquid in flowers feeds the bees?', answer: 'Nectar', options: ['Nectar', 'Honey', 'Sap', 'Dew'] },
      { id: 'pollen', emoji: '🟡', question: 'What powdery dust helps flowers make new seeds?', answer: 'Pollen', options: ['Pollen', 'Sand', 'Sugar', 'Salt'] },
      { id: 'stem', emoji: '🪴', question: 'What part of a plant holds it up straight?', answer: 'Stem', options: ['Stem', 'Root', 'Leaf', 'Branch'] },
      { id: 'garden', emoji: '🌳', question: 'Where do we plant flowers so they can grow?', answer: 'Garden', options: ['Garden', 'Forest', 'Pond', 'Desert'] },
      { id: 'sunlight', emoji: '☀️', question: 'What bright thing does a flower need to open and grow?', answer: 'Sunlight', options: ['Sunlight', 'Moonlight', 'Wind', 'Rain'] },
      { id: 'water', emoji: '💧', question: 'What do we give flowers to keep them alive?', answer: 'Water', options: ['Water', 'Milk', 'Juice', 'Sand'] }
    ]
  },
  shapes: {
    title: 'Shapes Quiz',
    completionEmoji: '⭐',
    completionMessage: 'You\'re a shapes master! 🔷',
    questions: [
      { id: 'circle', emoji: '⭕', question: 'What shape is this?', answer: 'Circle', options: ['Oval', 'Sphere', 'Circle', 'Ring'] },
      { id: 'square', emoji: '🟥', question: 'What shape has 4 equal sides?', answer: 'Square', options: ['Rectangle', 'Square', 'Rhombus', 'Trapezoid'] },
      { id: 'triangle', emoji: '🔺', question: 'What shape has 3 sides?', answer: 'Triangle', options: ['Pentagon', 'Triangle', 'Diamond', 'Hexagon'] },
      { id: 'hexagon', emoji: '⬡', question: 'A beehive cell is shaped like this. What shape?', answer: 'Hexagon', options: ['Octagon', 'Pentagon', 'Heptagon', 'Hexagon'] },
      { id: 'star', emoji: '⭐', question: 'What shape is this?', answer: 'Star', options: ['Sun', 'Cross', 'Star', 'Asterisk'] },
      { id: 'heart', emoji: '❤️', question: 'What shape is this?', answer: 'Heart', options: ['Diamond', 'Leaf', 'Heart', 'Shield'] },
      { id: 'octagon', emoji: '🔷', question: 'A stop sign is this shape. What is it?', answer: 'Octagon', options: ['Hexagon', 'Pentagon', 'Decagon', 'Octagon'] },
      { id: 'oval', emoji: '🥚', question: 'An egg is this shape. What do we call it?', answer: 'Oval', options: ['Circle', 'Oval', 'Sphere', 'Ellipse'] },
      { id: 'diamond', emoji: '💎', question: 'What shape is this?', answer: 'Diamond', options: ['Square', 'Rhombus', 'Diamond', 'Kite'] },
      { id: 'rectangle', emoji: '🟦', question: 'A door is shaped like this. What shape?', answer: 'Rectangle', options: ['Square', 'Rectangle', 'Parallelogram', 'Trapezoid'] },
      { id: 'crescent', emoji: '🌙', question: 'Which shape looks like a sliver of moon?', answer: 'Crescent', options: ['Crescent', 'Circle', 'Comma', 'Banana'] },
      { id: 'cone', emoji: '🍦', question: 'Which shape is pointy on top and round at the bottom?', answer: 'Cone', options: ['Cone', 'Triangle', 'Pyramid', 'Teardrop'] },
      { id: 'cube', emoji: '📦', question: 'Which shape is a box with six square faces?', answer: 'Cube', options: ['Cube', 'Square', 'Ball', 'Block'] },
      { id: 'sphere', emoji: '🔵', question: 'Which round shape is like a ball?', answer: 'Sphere', options: ['Sphere', 'Circle', 'Bubble', 'Egg'] },
      { id: 'pyramid', emoji: '⛰️', question: 'Which shape has a square base and a point at the top?', answer: 'Pyramid', options: ['Pyramid', 'Triangle', 'Cone', 'Mountain'] },
      { id: 'semicircle', emoji: '🌓', question: 'Which shape is half of a circle?', answer: 'Semicircle', options: ['Semicircle', 'Circle', 'Moon', 'Arch'] },
      { id: 'arrow', emoji: '➡️', question: 'Which shape points the way to go?', answer: 'Arrow', options: ['Arrow', 'Triangle', 'Spear', 'Pointer'] },
      { id: 'cross', emoji: '➕', question: 'Which shape looks like a plus sign?', answer: 'Cross', options: ['Cross', 'Plus', 'Star', 'X'] },
      { id: 'spiral', emoji: '🌀', question: 'Which shape curls round and round like a snail shell?', answer: 'Spiral', options: ['Spiral', 'Circle', 'Coil', 'Swirl'] },
      { id: 'ring', emoji: '💍', question: 'Which shape is a circle with a hole in the middle?', answer: 'Ring', options: ['Ring', 'Circle', 'Donut', 'Belt'] }
    ]
  },
  animals: {
    title: 'Animal Quiz',
    completionEmoji: '🦁',
    completionMessage: 'You\'re a wildlife expert! 🐼',
    questions: [
      { id: 'lion', emoji: '🦁', question: 'Which animal is known as the King of the Jungle?', answer: 'Lion', options: ['Tiger', 'Leopard', 'Lion', 'Cheetah'] },
      { id: 'elephant', emoji: '🐘', question: 'Which is the largest land animal?', answer: 'Elephant', options: ['Rhinoceros', 'Hippopotamus', 'Elephant', 'Giraffe'] },
      { id: 'giraffe', emoji: '🦒', question: 'Which animal has the longest neck?', answer: 'Giraffe', options: ['Camel', 'Giraffe', 'Ostrich', 'Horse'] },
      { id: 'monkey', emoji: '🐒', question: 'Which animal loves to swing on trees?', answer: 'Monkey', options: ['Squirrel', 'Monkey', 'Sloth', 'Koala'] },
      { id: 'dog', emoji: '🐶', question: 'Which animal is known as man\'s best friend?', answer: 'Dog', options: ['Cat', 'Rabbit', 'Dog', 'Fox'] },
      { id: 'dolphin', emoji: '🐬', question: 'Which smart sea animal can jump out of water?', answer: 'Dolphin', options: ['Shark', 'Whale', 'Seal', 'Dolphin'] },
      { id: 'panda', emoji: '🐼', question: 'This black-and-white bear loves bamboo. What is it?', answer: 'Panda', options: ['Raccoon', 'Badger', 'Panda', 'Skunk'] },
      { id: 'frog', emoji: '🐸', question: 'Which animal starts life as a tadpole?', answer: 'Frog', options: ['Toad', 'Frog', 'Salamander', 'Newt'] },
      { id: 'penguin', emoji: '🐧', question: 'Which bird cannot fly but loves to swim in cold places?', answer: 'Penguin', options: ['Ostrich', 'Penguin', 'Emu', 'Kiwi'] },
      { id: 'butterfly', emoji: '🦋', question: 'Which beautiful insect starts life as a caterpillar?', answer: 'Butterfly', options: ['Moth', 'Dragonfly', 'Bee', 'Butterfly'] },
      { id: 'rabbit', emoji: '🐰', question: 'Which animal has long ears and loves carrots?', answer: 'Rabbit', options: ['Rabbit', 'Cat', 'Dog', 'Bear'] },
      { id: 'cat', emoji: '🐱', question: 'Which animal says meow and purrs?', answer: 'Cat', options: ['Cat', 'Dog', 'Lion', 'Tiger'] },
      { id: 'cow', emoji: '🐮', question: 'Which farm animal gives us milk?', answer: 'Cow', options: ['Cow', 'Horse', 'Pig', 'Sheep'] },
      { id: 'horse', emoji: '🐴', question: 'Which animal neighs and loves to gallop?', answer: 'Horse', options: ['Horse', 'Donkey', 'Zebra', 'Camel'] },
      { id: 'sheep', emoji: '🐑', question: 'Which animal is covered in fluffy wool?', answer: 'Sheep', options: ['Sheep', 'Goat', 'Cloud', 'Lamb'] },
      { id: 'bear', emoji: '🐻', question: 'Which big animal loves honey and sleeps all winter?', answer: 'Bear', options: ['Bear', 'Wolf', 'Fox', 'Monkey'] },
      { id: 'tiger', emoji: '🐯', question: 'Which big cat has orange stripes?', answer: 'Tiger', options: ['Tiger', 'Lion', 'Leopard', 'Cat'] },
      { id: 'zebra', emoji: '🦓', question: 'Which animal has black-and-white stripes?', answer: 'Zebra', options: ['Zebra', 'Horse', 'Tiger', 'Cow'] },
      { id: 'snake', emoji: '🐍', question: 'Which animal slides along without any legs?', answer: 'Snake', options: ['Snake', 'Worm', 'Lizard', 'Eel'] },
      { id: 'whale', emoji: '🐳', question: 'Which huge animal sings songs in the ocean?', answer: 'Whale', options: ['Whale', 'Dolphin', 'Shark', 'Seal'] }
    ]
  },
  colors: {
    title: 'Colors Quiz',
    completionEmoji: '🎨',
    completionMessage: 'You\'re a color genius! 🌈',
    questions: [
      { id: 'red', emoji: '🍒', question: 'What color is this sweet cherry?', answer: 'Red', options: ['Blue', 'Green', 'Red', 'Yellow'] },
      { id: 'yellow', emoji: '🍌', question: 'What color is this ripe banana?', answer: 'Yellow', options: ['Purple', 'Yellow', 'Pink', 'Orange'] },
      { id: 'blue', emoji: '🐳', question: 'What color is this friendly whale?', answer: 'Blue', options: ['Green', 'Brown', 'Black', 'Blue'] },
      { id: 'green', emoji: '🐸', question: 'What color is this jumping frog?', answer: 'Green', options: ['Red', 'Orange', 'Green', 'White'] },
      { id: 'orange', emoji: '🍊', question: 'What color is this juicy orange?', answer: 'Orange', options: ['Yellow', 'Orange', 'Pink', 'Purple'] },
      { id: 'pink', emoji: '🦩', question: 'What color is this tall flamingo?', answer: 'Pink', options: ['Pink', 'Blue', 'Green', 'Brown'] },
      { id: 'purple', emoji: '🍇', question: 'What color are these sweet grapes?', answer: 'Purple', options: ['White', 'Yellow', 'Purple', 'Red'] },
      { id: 'brown', emoji: '🐻', question: 'What color is this cute teddy bear?', answer: 'Brown', options: ['Blue', 'Black', 'Orange', 'Brown'] },
      { id: 'white', emoji: '☃️', question: 'What color is this cold snowman?', answer: 'White', options: ['Green', 'White', 'Purple', 'Pink'] },
      { id: 'black', emoji: '🐈‍⬛', question: 'What color is this little cat?', answer: 'Black', options: ['Red', 'Yellow', 'Blue', 'Black'] },
      { id: 'gray', emoji: '🐘', question: 'What color is this big elephant?', answer: 'Gray', options: ['Gray', 'Pink', 'Green', 'Blue'] },
      { id: 'gold', emoji: '⭐', question: 'What color is this shiny star?', answer: 'Gold', options: ['Gold', 'Silver', 'Blue', 'Red'] },
      { id: 'silver', emoji: '🥈', question: 'What color is this second-place medal?', answer: 'Silver', options: ['Silver', 'Gold', 'Bronze', 'White'] },
      { id: 'rainbow', emoji: '🌈', question: 'What do we call all the colors together in the sky?', answer: 'Rainbow', options: ['Rainbow', 'Cloud', 'Sun', 'Star'] },
      { id: 'redheart', emoji: '❤️', question: 'What color is this love heart?', answer: 'Red', options: ['Red', 'Pink', 'Purple', 'Blue'] },
      { id: 'greenheart', emoji: '💚', question: 'What color is this heart?', answer: 'Green', options: ['Green', 'Blue', 'Yellow', 'Red'] },
      { id: 'blueheart', emoji: '💙', question: 'What color is this heart?', answer: 'Blue', options: ['Blue', 'Green', 'Purple', 'Black'] },
      { id: 'orangeheart', emoji: '🧡', question: 'What color is this heart?', answer: 'Orange', options: ['Orange', 'Yellow', 'Red', 'Pink'] },
      { id: 'sky', emoji: '🩵', question: 'What color is the clear daytime sky?', answer: 'Blue', options: ['Blue', 'Green', 'Pink', 'Gray'] },
      { id: 'grass', emoji: '🌱', question: 'What color is fresh green grass?', answer: 'Green', options: ['Green', 'Brown', 'Blue', 'Yellow'] }
    ]
  },
  vehicles: {
    title: 'Vehicles Quiz',
    completionEmoji: '🚗',
    completionMessage: 'You\'re a transportation expert! 🚀',
    questions: [
      { id: 'car', emoji: '🚗', question: 'What vehicle is this that drives on roads?', answer: 'Car', options: ['Bicycle', 'Train', 'Car', 'Boat'] },
      { id: 'airplane', emoji: '✈️', question: 'What vehicle flies high up in the sky?', answer: 'Airplane', options: ['Ship', 'Helicopter', 'Tractor', 'Airplane'] },
      { id: 'train', emoji: '🚂', question: 'What vehicle travels on tracks and goes choo-choo?', answer: 'Train', options: ['Train', 'Car', 'Bus', 'Submarine'] },
      { id: 'ship', emoji: '🚢', question: 'What large vehicle travels across deep oceans?', answer: 'Ship', options: ['Rocket', 'Bicycle', 'Ship', 'Helicopter'] },
      { id: 'bicycle', emoji: '🚲', question: 'What vehicle has two wheels and pedaling pedals?', answer: 'Bicycle', options: ['Motorcycle', 'Bicycle', 'Car', 'Train'] },
      { id: 'helicopter', emoji: '🚁', question: 'What vehicle flies using spinning blades on top?', answer: 'Helicopter', options: ['Airplane', 'Hot Air Balloon', 'Rocket', 'Helicopter'] },
      { id: 'rocket', emoji: '🚀', question: 'What powerful vehicle travels into outer space?', answer: 'Rocket', options: ['Submarine', 'Rocket', 'Train', 'Bus'] },
      { id: 'fireengine', emoji: '🚒', question: 'What red vehicle helps firefighters put out fires?', answer: 'Fire Engine', options: ['Ambulance', 'Police Car', 'Fire Engine', 'Tractor'] },
      { id: 'schoolbus', emoji: '🚌', question: 'What yellow vehicle takes children to school?', answer: 'School Bus', options: ['School Bus', 'Truck', 'Airplane', 'Car'] },
      { id: 'tractor', emoji: '🚜', question: 'What vehicle does a farmer use on a field?', answer: 'Tractor', options: ['Bicycle', 'Boat', 'Submarine', 'Tractor'] },
      { id: 'ambulance', emoji: '🚑', question: 'Which vehicle rushes sick people to the hospital?', answer: 'Ambulance', options: ['Ambulance', 'Fire Engine', 'Police Car', 'Taxi'] },
      { id: 'policecar', emoji: '🚓', question: 'Which vehicle do police officers drive to help keep us safe?', answer: 'Police Car', options: ['Police Car', 'Ambulance', 'Taxi', 'Bus'] },
      { id: 'taxi', emoji: '🚕', question: 'Which yellow car do you pay to ride across the city?', answer: 'Taxi', options: ['Taxi', 'Bus', 'Car', 'Van'] },
      { id: 'truck', emoji: '🚚', question: 'Which big vehicle carries heavy loads on the road?', answer: 'Truck', options: ['Truck', 'Car', 'Bicycle', 'Scooter'] },
      { id: 'motorcycle', emoji: '🏍️', question: 'Which fast two-wheeled vehicle has an engine?', answer: 'Motorcycle', options: ['Motorcycle', 'Bicycle', 'Scooter', 'Car'] },
      { id: 'submarine', emoji: '🤿', question: 'Which vehicle travels deep under the water?', answer: 'Submarine', options: ['Submarine', 'Ship', 'Boat', 'Rocket'] },
      { id: 'sailboat', emoji: '⛵', question: 'Which boat uses the wind in its sails to move?', answer: 'Sailboat', options: ['Sailboat', 'Ship', 'Canoe', 'Ferry'] },
      { id: 'balloon', emoji: '🎈', question: 'Which flying vehicle floats up using hot air?', answer: 'Hot Air Balloon', options: ['Hot Air Balloon', 'Airplane', 'Kite', 'Helicopter'] },
      { id: 'scooter', emoji: '🛵', question: 'Which small two-wheeler is great for zipping around town?', answer: 'Scooter', options: ['Scooter', 'Truck', 'Train', 'Bus'] },
      { id: 'van', emoji: '🚐', question: 'Which vehicle can carry a whole family and lots of bags?', answer: 'Van', options: ['Van', 'Bicycle', 'Motorcycle', 'Rocket'] }
    ]
  },
  birds: {
    title: 'Bird Quiz',
    completionEmoji: '🐦',
    completionMessage: 'You\'re a bird expert! 🦉',
    questions: [
      { id: 'bird', emoji: '🐦', question: 'Which animal has feathers and can fly?', answer: 'Bird', options: ['Bird', 'Bat', 'Bee', 'Butterfly'] },
      { id: 'eagle', emoji: '🦅', question: 'Which bird is known as the king of the sky?', answer: 'Eagle', options: ['Hawk', 'Crow', 'Eagle', 'Owl'] },
      { id: 'owl', emoji: '🦉', question: 'Which bird is awake at night and calls "hoot"?', answer: 'Owl', options: ['Parrot', 'Duck', 'Owl', 'Sparrow'] },
      { id: 'parrot', emoji: '🦜', question: 'Which colorful bird can copy your words?', answer: 'Parrot', options: ['Crow', 'Pigeon', 'Robin', 'Parrot'] },
      { id: 'duck', emoji: '🦆', question: 'Which bird says "quack"?', answer: 'Duck', options: ['Goose', 'Duck', 'Swan', 'Heron'] },
      { id: 'swan', emoji: '🦢', question: 'Which graceful white bird glides on lakes?', answer: 'Swan', options: ['Swan', 'Goose', 'Crane', 'Pelican'] },
      { id: 'chick', emoji: '🐤', question: 'What do we call a baby chicken?', answer: 'Chick', options: ['Duckling', 'Chick', 'Cygnet', 'Kitten'] },
      { id: 'goose', emoji: '🪿', question: 'Which bird flies in a V and says "honk"?', answer: 'Goose', options: ['Duck', 'Swan', 'Goose', 'Crow'] },
      { id: 'rooster', emoji: '🐓', question: 'Which bird wakes us with "cock-a-doodle-doo"?', answer: 'Rooster', options: ['Hen', 'Turkey', 'Rooster', 'Peacock'] },
      { id: 'peacock', emoji: '🦚', question: 'Which bird shows off a big fan of feathers?', answer: 'Peacock', options: ['Turkey', 'Pheasant', 'Ostrich', 'Peacock'] },
      { id: 'penguin', emoji: '🐧', question: 'Which black-and-white bird waddles and swims in the cold?', answer: 'Penguin', options: ['Penguin', 'Puffin', 'Seal', 'Duck'] },
      { id: 'flamingo', emoji: '🦩', question: 'Which tall pink bird stands on one leg?', answer: 'Flamingo', options: ['Flamingo', 'Crane', 'Stork', 'Heron'] },
      { id: 'turkey', emoji: '🦃', question: 'Which big bird gobbles and fans its tail?', answer: 'Turkey', options: ['Turkey', 'Chicken', 'Peacock', 'Goose'] },
      { id: 'dove', emoji: '🕊️', question: 'Which white bird is a symbol of peace?', answer: 'Dove', options: ['Dove', 'Seagull', 'Pigeon', 'Swan'] },
      { id: 'ostrich', emoji: '🪶', question: 'Which is the biggest bird that runs but cannot fly?', answer: 'Ostrich', options: ['Ostrich', 'Emu', 'Eagle', 'Turkey'] },
      { id: 'hen', emoji: '🐔', question: 'Which farm bird lays eggs and says "cluck"?', answer: 'Hen', options: ['Hen', 'Rooster', 'Duck', 'Goose'] },
      { id: 'nest', emoji: '🪹', question: 'Where does a bird lay its eggs?', answer: 'Nest', options: ['Nest', 'Cage', 'Hole', 'Box'] },
      { id: 'feather', emoji: '🪶', question: 'What soft, light thing covers a bird\'s body?', answer: 'Feathers', options: ['Feathers', 'Fur', 'Scales', 'Wool'] },
      { id: 'wing', emoji: '🐦', question: 'Which body part helps a bird fly?', answer: 'Wings', options: ['Wings', 'Legs', 'Beak', 'Tail'] },
      { id: 'egg', emoji: '🥚', question: 'What do birds hatch out of?', answer: 'Egg', options: ['Egg', 'Seed', 'Cocoon', 'Shell'] }
    ]
  },
  vegetables: {
    title: 'Vegetable Quiz',
    completionEmoji: '🥕',
    completionMessage: 'You eat your veggies like a pro! 🥦',
    questions: [
      { id: 'carrot', emoji: '🥕', question: 'Which vegetable is long and orange?', answer: 'Carrot', options: ['Radish', 'Carrot', 'Corn', 'Banana'] },
      { id: 'broccoli', emoji: '🥦', question: 'Which green vegetable looks like tiny trees?', answer: 'Broccoli', options: ['Broccoli', 'Cabbage', 'Lettuce', 'Spinach'] },
      { id: 'tomato', emoji: '🍅', question: 'Which red vegetable is often called a fruit?', answer: 'Tomato', options: ['Apple', 'Tomato', 'Pepper', 'Cherry'] },
      { id: 'cucumber', emoji: '🥒', question: 'Which green vegetable is pickled into pickles?', answer: 'Cucumber', options: ['Zucchini', 'Celery', 'Cucumber', 'Bean'] },
      { id: 'corn', emoji: '🌽', question: 'Which yellow vegetable do we eat at a barbecue?', answer: 'Corn', options: ['Corn', 'Carrot', 'Potato', 'Pea'] },
      { id: 'potato', emoji: '🥔', question: 'Which brown vegetable grows underground?', answer: 'Potato', options: ['Onion', 'Potato', 'Turnip', 'Radish'] },
      { id: 'onion', emoji: '🧅', question: 'Which vegetable makes you cry when you cut it?', answer: 'Onion', options: ['Garlic', 'Leek', 'Onion', 'Shallot'] },
      { id: 'lettuce', emoji: '🥬', question: 'Which leafy green vegetable goes in salads?', answer: 'Lettuce', options: ['Cabbage', 'Spinach', 'Lettuce', 'Kale'] },
      { id: 'pepper', emoji: '🫑', question: 'Which vegetable can be green, red, or yellow and is crunchy?', answer: 'Pepper', options: ['Chili', 'Pepper', 'Tomato', 'Carrot'] },
      { id: 'eggplant', emoji: '🍆', question: 'Which purple vegetable is shaped like an egg?', answer: 'Eggplant', options: ['Plum', 'Beet', 'Eggplant', 'Grape'] },
      { id: 'peas', emoji: '🫛', question: 'Which little green balls grow in a pod?', answer: 'Peas', options: ['Peas', 'Beans', 'Grapes', 'Corn'] },
      { id: 'mushroom', emoji: '🍄', question: 'Which vegetable grows with a little umbrella cap?', answer: 'Mushroom', options: ['Mushroom', 'Onion', 'Cabbage', 'Turnip'] },
      { id: 'garlic', emoji: '🧄', question: 'Which white bulb makes food tasty and smells strong?', answer: 'Garlic', options: ['Garlic', 'Onion', 'Ginger', 'Radish'] },
      { id: 'chili', emoji: '🌶️', question: 'Which red vegetable is very spicy and hot?', answer: 'Chili', options: ['Chili', 'Pepper', 'Tomato', 'Carrot'] },
      { id: 'sweetpotato', emoji: '🍠', question: 'Which sweet orange vegetable grows underground?', answer: 'Sweet Potato', options: ['Sweet Potato', 'Potato', 'Carrot', 'Pumpkin'] },
      { id: 'pumpkin', emoji: '🎃', question: 'Which big orange vegetable is carved at Halloween?', answer: 'Pumpkin', options: ['Pumpkin', 'Melon', 'Squash', 'Orange'] },
      { id: 'spinach', emoji: '🥬', question: 'Which leafy green made Popeye strong?', answer: 'Spinach', options: ['Spinach', 'Lettuce', 'Cabbage', 'Kale'] },
      { id: 'beet', emoji: '🫜', question: 'Which deep red root vegetable stains your fingers pink?', answer: 'Beetroot', options: ['Beetroot', 'Radish', 'Turnip', 'Carrot'] },
      { id: 'ginger', emoji: '🫚', question: 'Which knobbly root adds a warm, zingy taste to food?', answer: 'Ginger', options: ['Ginger', 'Garlic', 'Potato', 'Onion'] },
      { id: 'cabbage', emoji: '🥬', question: 'Which round leafy vegetable has many tight layers?', answer: 'Cabbage', options: ['Cabbage', 'Lettuce', 'Onion', 'Spinach'] }
    ]
  },
  insects: {
    title: 'Insect Quiz',
    completionEmoji: '🐞',
    completionMessage: 'You\'re a bug expert! 🐝',
    questions: [
      { id: 'butterfly', emoji: '🦋', question: 'Which insect has colourful wings and starts as a caterpillar?', answer: 'Butterfly', options: ['Moth', 'Dragonfly', 'Butterfly', 'Bee'] },
      { id: 'ladybug', emoji: '🐞', question: 'Which small red bug has black spots?', answer: 'Ladybug', options: ['Beetle', 'Ladybug', 'Ant', 'Spider'] },
      { id: 'bee', emoji: '🐝', question: 'Which insect makes honey and has yellow stripes?', answer: 'Bee', options: ['Wasp', 'Fly', 'Bee', 'Mosquito'] },
      { id: 'ant', emoji: '🐜', question: 'Which tiny insect loves to carry crumbs in a line?', answer: 'Ant', options: ['Ant', 'Termite', 'Beetle', 'Bug'] },
      { id: 'spider', emoji: '🕷️', question: 'Which eight-legged crawler spins a web?', answer: 'Spider', options: ['Spider', 'Beetle', 'Cricket', 'Snail'] },
      { id: 'beetle', emoji: '🪲', question: 'Which shiny bug has a hard shell on its back?', answer: 'Beetle', options: ['Ladybug', 'Roach', 'Beetle', 'Ant'] },
      { id: 'snail', emoji: '🐌', question: 'Which slow crawler carries its home on its back?', answer: 'Snail', options: ['Worm', 'Slug', 'Snail', 'Caterpillar'] },
      { id: 'caterpillar', emoji: '🐛', question: 'Which wiggly bug turns into a butterfly?', answer: 'Caterpillar', options: ['Worm', 'Caterpillar', 'Grub', 'Snail'] },
      { id: 'mosquito', emoji: '🦟', question: 'Which buzzing bug leaves an itchy bite?', answer: 'Mosquito', options: ['Fly', 'Bee', 'Mosquito', 'Beetle'] },
      { id: 'cricket', emoji: '🦗', question: 'Which bug chirps at night with its legs?', answer: 'Cricket', options: ['Grasshopper', 'Cricket', 'Beetle', 'Ant'] },
      { id: 'grasshopper', emoji: '🦗', question: 'Which green bug hops far with its long back legs?', answer: 'Grasshopper', options: ['Grasshopper', 'Cricket', 'Frog', 'Locust'] },
      { id: 'dragonfly', emoji: '🪰', question: 'Which insect has long see-through wings and hovers over ponds?', answer: 'Dragonfly', options: ['Dragonfly', 'Fly', 'Butterfly', 'Bee'] },
      { id: 'fly', emoji: '🪰', question: 'Which buzzing insect lands on your food?', answer: 'Fly', options: ['Fly', 'Bee', 'Mosquito', 'Wasp'] },
      { id: 'worm', emoji: '🪱', question: 'Which long, wiggly crawler lives in the soil?', answer: 'Worm', options: ['Worm', 'Snake', 'Caterpillar', 'Slug'] },
      { id: 'firefly', emoji: '✨', question: 'Which bug glows and blinks with light at night?', answer: 'Firefly', options: ['Firefly', 'Moth', 'Beetle', 'Fly'] },
      { id: 'moth', emoji: '🦋', question: 'Which night-time insect flutters toward lamps?', answer: 'Moth', options: ['Moth', 'Butterfly', 'Bee', 'Fly'] },
      { id: 'wasp', emoji: '🐝', question: 'Which yellow-and-black insect can sting but makes no honey?', answer: 'Wasp', options: ['Wasp', 'Bee', 'Hornet', 'Fly'] },
      { id: 'termite', emoji: '🐜', question: 'Which tiny insect builds tall mounds and eats wood?', answer: 'Termite', options: ['Termite', 'Ant', 'Beetle', 'Bug'] },
      { id: 'cocoon', emoji: '🛡️', question: 'What silky case does a caterpillar make before becoming a moth?', answer: 'Cocoon', options: ['Cocoon', 'Nest', 'Web', 'Shell'] },
      { id: 'honeycomb', emoji: '🍯', question: 'What waxy home do bees build to store honey?', answer: 'Honeycomb', options: ['Honeycomb', 'Web', 'Nest', 'Hive Hole'] }
    ]
  },
  space: {
    title: 'Space Quiz',
    completionEmoji: '🚀',
    completionMessage: 'You\'re a space explorer! 🌟',
    questions: [
      { id: 'rocket', emoji: '🚀', question: 'What vehicle blasts off into space?', answer: 'Rocket', options: ['Airplane', 'Rocket', 'Car', 'Boat'] },
      { id: 'moon', emoji: '🌙', question: 'What shines in the night sky and has craters?', answer: 'Moon', options: ['Sun', 'Star', 'Moon', 'Comet'] },
      { id: 'sun', emoji: '☀️', question: 'What is the big bright star at the center of our solar system?', answer: 'Sun', options: ['Sun', 'Planet', 'Moon', 'Light'] },
      { id: 'saturn', emoji: '🪐', question: 'Which planet is famous for its big bright rings?', answer: 'Saturn', options: ['Jupiter', 'Mars', 'Saturn', 'Earth'] },
      { id: 'astronaut', emoji: '🧑‍🚀', question: 'Who travels to space in a special suit?', answer: 'Astronaut', options: ['Pilot', 'Astronaut', 'Scientist', 'Captain'] },
      { id: 'star', emoji: '⭐', question: 'What twinkles far away in the night sky?', answer: 'Star', options: ['Star', 'Moon', 'Comet', 'Spark'] },
      { id: 'earth', emoji: '🌍', question: 'Which blue and green planet is our home?', answer: 'Earth', options: ['Mars', 'Earth', 'Venus', 'Moon'] },
      { id: 'comet', emoji: '☄️', question: 'What streaks across the sky with a glowing tail?', answer: 'Comet', options: ['Meteor', 'Comet', 'Rocket', 'Star'] },
      { id: 'alien', emoji: '👽', question: 'What friendly being might live on another planet?', answer: 'Alien', options: ['Monster', 'Robot', 'Alien', 'Ghost'] },
      { id: 'shooting-star', emoji: '🌠', question: 'What do we call a star that quickly falls through the sky?', answer: 'Shooting Star', options: ['Shooting Star', 'Comet', 'Spark', 'Moon'] },
      { id: 'mars', emoji: '🔴', question: 'Which planet is known as the Red Planet?', answer: 'Mars', options: ['Mars', 'Jupiter', 'Venus', 'Mercury'] },
      { id: 'jupiter', emoji: '🪐', question: 'Which is the biggest planet in our solar system?', answer: 'Jupiter', options: ['Jupiter', 'Saturn', 'Earth', 'Neptune'] },
      { id: 'telescope', emoji: '🔭', question: 'What tool helps us see stars and planets up close?', answer: 'Telescope', options: ['Telescope', 'Microscope', 'Binoculars', 'Camera'] },
      { id: 'satellite', emoji: '🛰️', question: 'What machine circles Earth to send TV and phone signals?', answer: 'Satellite', options: ['Satellite', 'Rocket', 'Star', 'Drone'] },
      { id: 'galaxy', emoji: '🌌', question: 'What do we call a huge group of billions of stars?', answer: 'Galaxy', options: ['Galaxy', 'Planet', 'Comet', 'Cloud'] },
      { id: 'spacesuit', emoji: '👨‍🚀', question: 'What special outfit keeps astronauts safe in space?', answer: 'Spacesuit', options: ['Spacesuit', 'Raincoat', 'Uniform', 'Costume'] },
      { id: 'ufo', emoji: '🛸', question: 'What do we call a mysterious flying saucer in the sky?', answer: 'UFO', options: ['UFO', 'Plane', 'Kite', 'Rocket'] },
      { id: 'crater', emoji: '🌑', question: 'What do we call the round dents and holes on the Moon?', answer: 'Craters', options: ['Craters', 'Hills', 'Ponds', 'Caves'] },
      { id: 'orbit', emoji: '🔄', question: 'What do we call the path a planet takes around the Sun?', answer: 'Orbit', options: ['Orbit', 'Road', 'Track', 'Loop'] },
      { id: 'planet', emoji: '🌎', question: 'What do we call a big round world that circles the Sun?', answer: 'Planet', options: ['Planet', 'Star', 'Moon', 'Comet'] }
    ]
  },
  dinosaurs: {
    title: 'Dinosaur Quiz',
    completionEmoji: '🦖',
    completionMessage: 'You are a dino expert! Rawr! 🦕',
    questions: [
      { id: 'trex', emoji: '🦖', question: 'Which dinosaur was the fierce king with big sharp teeth?', answer: 'T-Rex', options: ['Stegosaurus', 'T-Rex', 'Brachiosaurus', 'Triceratops'] },
      { id: 'triceratops', emoji: '🦏', question: 'Which dinosaur had three big horns on its face?', answer: 'Triceratops', options: ['Triceratops', 'Rhino', 'Ankylosaurus', 'Stegosaurus'] },
      { id: 'stegosaurus', emoji: '🐉', question: 'Which dinosaur had bony plates along its back?', answer: 'Stegosaurus', options: ['Stegosaurus', 'T-Rex', 'Pterodactyl', 'Iguanodon'] },
      { id: 'brachiosaurus', emoji: '🦕', question: 'Which giant dinosaur had a very long neck?', answer: 'Brachiosaurus', options: ['Brachiosaurus', 'Triceratops', 'Velociraptor', 'Ankylosaurus'] },
      { id: 'pterodactyl', emoji: '🦅', question: 'Which prehistoric creature flew in the sky with wings?', answer: 'Pterodactyl', options: ['Pterodactyl', 'Eagle', 'Bat', 'Brachiosaurus'] },
      { id: 'ankylosaurus', emoji: '🐢', question: 'Which dinosaur wore bony armor and a club tail?', answer: 'Ankylosaurus', options: ['Ankylosaurus', 'Triceratops', 'Turtle', 'Stegosaurus'] },
      { id: 'fossils', emoji: '🦴', question: 'What do we call the hardened remains of dinosaurs we dig up?', answer: 'Fossils', options: ['Fossils', 'Bones', 'Rocks', 'Shells'] },
      { id: 'dino-eggs', emoji: '🥚', question: 'What did baby dinosaurs hatch out of long ago?', answer: 'Dinosaur Eggs', options: ['Dinosaur Eggs', 'Nests', 'Seeds', 'Rocks'] },
      { id: 'herbivores', emoji: '🌿', question: 'What do we call dinosaurs that ate only plants?', answer: 'Herbivores', options: ['Herbivores', 'Carnivores', 'Omnivores', 'Mammals'] },
      { id: 'velociraptor', emoji: '🐊', question: 'Which small, fast dinosaur hunted in packs with sharp claws?', answer: 'Velociraptor', options: ['Velociraptor', 'T-Rex', 'Crocodile', 'Compsognathus'] },
      { id: 'spinosaurus', emoji: '🐊', question: 'Which dinosaur had a big sail on its back and loved water?', answer: 'Spinosaurus', options: ['Spinosaurus', 'Stegosaurus', 'T-Rex', 'Diplodocus'] },
      { id: 'diplodocus', emoji: '🦕', question: 'Which very long dinosaur had a whip-like tail?', answer: 'Diplodocus', options: ['Diplodocus', 'Brachiosaurus', 'Triceratops', 'T-Rex'] },
      { id: 'carnivore', emoji: '🥩', question: 'What do we call dinosaurs that ate meat?', answer: 'Carnivores', options: ['Carnivores', 'Herbivores', 'Omnivores', 'Insects'] },
      { id: 'volcano', emoji: '🌋', question: 'Which fiery mountain erupted during the age of dinosaurs?', answer: 'Volcano', options: ['Volcano', 'Mountain', 'Hill', 'Cave'] },
      { id: 'paleontologist', emoji: '🧑‍🔬', question: 'What do we call a scientist who digs up dinosaur bones?', answer: 'Paleontologist', options: ['Paleontologist', 'Astronaut', 'Zookeeper', 'Doctor'] },
      { id: 'claws', emoji: '🦅', question: 'What sharp body part did raptors use to grab prey?', answer: 'Claws', options: ['Claws', 'Wings', 'Horns', 'Fins'] },
      { id: 'extinct', emoji: '💫', question: 'What word means the dinosaurs all disappeared long ago?', answer: 'Extinct', options: ['Extinct', 'Sleeping', 'Hiding', 'Tiny'] },
      { id: 'pteranodon', emoji: '🦇', question: 'Which flying reptile had a long crest on its head?', answer: 'Pteranodon', options: ['Pteranodon', 'Pterodactyl', 'Bat', 'Eagle'] },
      { id: 'iguanodon', emoji: '🦎', question: 'Which plant-eating dinosaur had a spiky thumb?', answer: 'Iguanodon', options: ['Iguanodon', 'Iguana', 'Stegosaurus', 'T-Rex'] },
      { id: 'dinofootprint', emoji: '🐾', question: 'What did dinosaurs leave in the mud that turned to stone?', answer: 'Footprints', options: ['Footprints', 'Feathers', 'Scales', 'Eggs'] }
    ]
  },
  'sea-creatures': {
    title: 'Sea Creatures Quiz',
    completionEmoji: '🐙',
    completionMessage: 'You are an ocean explorer! 🌊',
    questions: [
      { id: 'octopus', emoji: '🐙', question: 'Which sea animal has eight wiggly arms?', answer: 'Octopus', options: ['Octopus', 'Squid', 'Crab', 'Starfish'] },
      { id: 'shark', emoji: '🦈', question: 'Which ocean hunter has sharp teeth and a fin on top?', answer: 'Shark', options: ['Shark', 'Dolphin', 'Whale', 'Swordfish'] },
      { id: 'whale', emoji: '🐳', question: 'Which is the biggest animal that lives in the sea?', answer: 'Whale', options: ['Whale', 'Shark', 'Dolphin', 'Seal'] },
      { id: 'starfish', emoji: '⭐', question: 'Which sea creature has five arms and lives on the seabed?', answer: 'Starfish', options: ['Starfish', 'Jellyfish', 'Crab', 'Snail'] },
      { id: 'crab', emoji: '🦀', question: 'Which sea animal walks sideways with claws?', answer: 'Crab', options: ['Crab', 'Lobster', 'Shrimp', 'Octopus'] },
      { id: 'seahorse', emoji: '🐴', question: 'Which tiny sea creature looks like a little horse?', answer: 'Seahorse', options: ['Seahorse', 'Horse', 'Dolphin', 'Eel'] },
      { id: 'jellyfish', emoji: '🪼', question: 'Which sea creature drifts with soft, stinging tentacles?', answer: 'Jellyfish', options: ['Jellyfish', 'Squid', 'Coral', 'Octopus'] },
      { id: 'dolphin', emoji: '🐬', question: 'Which smart, friendly sea animal loves to leap and click?', answer: 'Dolphin', options: ['Dolphin', 'Shark', 'Whale', 'Seal'] },
      { id: 'sea-turtle', emoji: '🐢', question: 'Which shelled reptile swims slowly in the ocean?', answer: 'Sea Turtle', options: ['Sea Turtle', 'Tortoise', 'Frog', 'Crab'] },
      { id: 'fish', emoji: '🐠', question: 'Which colorful sea animal has scales and breathes through gills?', answer: 'Fish', options: ['Fish', 'Whale', 'Dolphin', 'Shrimp'] },
      { id: 'lobster', emoji: '🦞', question: 'Which red sea creature has big claws and a long tail?', answer: 'Lobster', options: ['Lobster', 'Crab', 'Shrimp', 'Scorpion'] },
      { id: 'shrimp', emoji: '🦐', question: 'Which tiny curled sea creature turns pink when cooked?', answer: 'Shrimp', options: ['Shrimp', 'Crab', 'Lobster', 'Snail'] },
      { id: 'squid', emoji: '🦑', question: 'Which long sea creature has ten arms and squirts ink?', answer: 'Squid', options: ['Squid', 'Octopus', 'Eel', 'Jellyfish'] },
      { id: 'seal', emoji: '🦭', question: 'Which flippered animal barks and slides on the beach?', answer: 'Seal', options: ['Seal', 'Walrus', 'Otter', 'Dolphin'] },
      { id: 'coral', emoji: '🪸', question: 'What colorful reef do many sea animals call home?', answer: 'Coral', options: ['Coral', 'Seaweed', 'Rock', 'Sponge'] },
      { id: 'clownfish', emoji: '🐡', question: 'Which orange-and-white fish lives among sea anemones?', answer: 'Clownfish', options: ['Clownfish', 'Goldfish', 'Pufferfish', 'Tuna'] },
      { id: 'pufferfish', emoji: '🐡', question: 'Which fish puffs up into a spiky ball when scared?', answer: 'Pufferfish', options: ['Pufferfish', 'Clownfish', 'Blowfish', 'Sunfish'] },
      { id: 'eel', emoji: '🐍', question: 'Which long, snake-like fish hides in ocean rocks?', answer: 'Eel', options: ['Eel', 'Snake', 'Worm', 'Seahorse'] },
      { id: 'seaweed', emoji: '🌿', question: 'Which green plant sways underwater and feeds sea animals?', answer: 'Seaweed', options: ['Seaweed', 'Grass', 'Coral', 'Moss'] },
      { id: 'walrus', emoji: '🦭', question: 'Which big sea animal has two long tusks and whiskers?', answer: 'Walrus', options: ['Walrus', 'Seal', 'Sea Lion', 'Whale'] }
    ]
  },
  'world-wonders': {
    title: 'World Wonders Quiz',
    completionEmoji: '🏛️',
    completionMessage: 'You are a master world explorer! 🌍✈️',
    questions: [
      { id: 'great-wall', emoji: '🧱', question: 'Which giant wall stretches across northern China?', answer: 'Great Wall of China', options: ['Berlin Wall', 'Great Wall of China', 'Hadrian’s Wall', 'Western Wall'] },
      { id: 'eiffel-tower', emoji: '🗼', question: 'In which city can you visit the famous Eiffel Tower?', answer: 'Paris', options: ['London', 'Rome', 'Paris', 'Madrid'] },
      { id: 'pyramids', emoji: '🔺', question: 'Which ancient stone structures were built in Egypt for Pharaohs?', answer: 'Pyramids of Giza', options: ['Ziggurats', 'Parthenon', 'Colosseum', 'Pyramids of Giza'] },
      { id: 'taj-mahal', emoji: '🕌', question: 'Which famous white marble mausoleum is located in Agra, India?', answer: 'Taj Mahal', options: ['Red Fort', 'Taj Mahal', 'Lotus Temple', 'Hawa Mahal'] },
      { id: 'statue-of-liberty', emoji: '🗽', question: 'Which famous green statue stands in New York Harbor?', answer: 'Statue of Liberty', options: ['Little Mermaid', 'Christ the Redeemer', 'Statue of Liberty', 'Sphinx'] },
      { id: 'colosseum', emoji: '🏛️', question: 'Which ancient amphitheater was used for gladiator games in Rome?', answer: 'Colosseum', options: ['Colosseum', 'Parthenon', 'Pantheon', 'Acropolis'] },
      { id: 'big-ben', emoji: '🕰️', question: 'Which famous clock tower stands near Parliament in London?', answer: 'Big Ben', options: ['Eiffel Tower', 'Pisa Tower', 'Big Ben', 'Clock Tower'] },
      { id: 'machu-picchu', emoji: '⛰️', question: 'Which ancient Inca citadel sits high in the Andes mountains of Peru?', answer: 'Machu Picchu', options: ['Chichen Itza', 'Machu Picchu', 'Tikal', 'Petra'] },
      { id: 'everest', emoji: '🏔️', question: 'What is the highest mountain peak above sea level in the world?', answer: 'Mount Everest', options: ['K2', 'Kilimanjaro', 'Mont Blanc', 'Mount Everest'] },
      { id: 'sydney-opera', emoji: '🎭', question: 'Which famous building in Australia looks like white sails on the harbor?', answer: 'Sydney Opera House', options: ['Harbour Bridge', 'Sydney Opera House', 'Sky Tower', 'Tower Bridge'] },
      { id: 'leaning-tower', emoji: '🏗️', question: 'Which famous bell tower in Italy is known for leaning to one side?', answer: 'Leaning Tower of Pisa', options: ['Colosseum', 'Leaning Tower of Pisa', 'Florence Duomo', 'St. Mark Campanile'] },
      { id: 'amazon-rainforest', emoji: '🌳', question: 'What is the largest tropical rainforest in the world?', answer: 'Amazon Rainforest', options: ['Congo Basin', 'Daintree', 'Amazon Rainforest', 'Boreal Forest'] },
      { id: 'grand-canyon', emoji: '🏜️', question: 'Which massive red-rock canyon was carved by the Colorado River in the USA?', answer: 'Grand Canyon', options: ['Grand Canyon', 'Bryce Canyon', 'Zion Canyon', 'Fish River Canyon'] },
      { id: 'christ-redeemer', emoji: '🗿', question: 'Which giant statue of Jesus stands atop Mount Corcovado in Rio de Janeiro?', answer: 'Christ the Redeemer', options: ['Statue of Liberty', 'Christ the Redeemer', 'Moai Statues', 'Sphinx'] },
      { id: 'niagara-falls', emoji: '🌊', question: 'Which massive waterfalls straddle the border of Canada and the USA?', answer: 'Niagara Falls', options: ['Victoria Falls', 'Iguazu Falls', 'Niagara Falls', 'Angel Falls'] },
      { id: 'stonehenge', emoji: '🪨', question: 'Which prehistoric circle of giant standing stones is located in England?', answer: 'Stonehenge', options: ['Easter Island', 'Stonehenge', 'Carnac Stones', 'Gobekli Tepe'] },
      { id: 'barrier-reef', emoji: '🐠', question: 'What is the world’s largest coral reef system off Australia’s coast?', answer: 'Great Barrier Reef', options: ['Mesoamerican Reef', 'Red Sea Reef', 'Fiji Reef', 'Great Barrier Reef'] },
      { id: 'fuji', emoji: '🌋', question: 'Which iconic snow-capped volcano is the highest mountain in Japan?', answer: 'Mount Fuji', options: ['Mount Vesuvius', 'Mount Fuji', 'Mount Etna', 'Kilauea'] },
      { id: 'tower-bridge', emoji: '🌉', question: 'Which famous bascule bridge crosses the River Thames in London?', answer: 'Tower Bridge', options: ['Golden Gate Bridge', 'Brooklyn Bridge', 'Tower Bridge', 'Sydney Harbour Bridge'] },
      { id: 'golden-gate', emoji: '🌉', question: 'Which iconic orange suspension bridge connects San Francisco to Marin County?', answer: 'Golden Gate Bridge', options: ['Golden Gate Bridge', 'Brooklyn Bridge', 'Akashi Kaikyo', 'Tower Bridge'] }
    ]
  },
  inventions: {
    title: 'Inventions & Discoveries Quiz',
    completionEmoji: '💡',
    completionMessage: 'You are a genius inventor! 🧠⚙️',
    questions: [
      { id: 'light-bulb', emoji: '💡', question: 'Who is famous for inventing the practical electric light bulb?', answer: 'Thomas Edison', options: ['Nikola Tesla', 'Thomas Edison', 'Alexander Bell', 'Benjamin Franklin'] },
      { id: 'airplane', emoji: '✈️', question: 'Which brothers built and flew the first successful motor airplane in 1903?', answer: 'Wright Brothers', options: ['Montgolfier Brothers', 'McDonald Brothers', 'Wright Brothers', 'Warner Brothers'] },
      { id: 'telephone', emoji: '📞', question: 'Who invented the first practical telephone to speak across distances?', answer: 'Alexander Graham Bell', options: ['Alexander Graham Bell', 'Thomas Edison', 'Guglielmo Marconi', 'Samuel Morse'] },
      { id: 'gravity', emoji: '🍎', question: 'Which scientist discovered the law of gravity after watching an apple fall?', answer: 'Isaac Newton', options: ['Albert Einstein', 'Galileo Galilei', 'Isaac Newton', 'Charles Darwin'] },
      { id: 'computer', emoji: '💻', question: 'Who is considered the "Father of the Computer" for designing the Mechanical Engine?', answer: 'Charles Babbage', options: ['Alan Turing', 'Charles Babbage', 'Bill Gates', 'Steve Jobs'] },
      { id: 'printing-press', emoji: '📰', question: 'Who invented the movable type printing press in Europe around 1440?', answer: 'Johannes Gutenberg', options: ['Leonardo da Vinci', 'Marco Polo', 'Johannes Gutenberg', 'Benjamin Franklin'] },
      { id: 'telescope', emoji: '🔭', question: 'Which astronomer improved the telescope to discover Jupiter’s four moons?', answer: 'Galileo Galilei', options: ['Galileo Galilei', 'Nicolaus Copernicus', 'Johannes Kepler', 'Isaac Newton'] },
      { id: 'electricity', emoji: '⚡', question: 'Who flew a kite during a thunderstorm to prove lightning is electricity?', answer: 'Benjamin Franklin', options: ['Thomas Edison', 'Benjamin Franklin', 'Nikola Tesla', 'Michael Faraday'] },
      { id: 'penicillin', emoji: '💊', question: 'Who discovered penicillin, the world’s first life-saving antibiotic?', answer: 'Alexander Fleming', options: ['Louis Pasteur', 'Robert Koch', 'Edward Jenner', 'Alexander Fleming'] },
      { id: 'steam-engine', emoji: '🚂', question: 'Who improved the steam engine, paving the way for the Industrial Revolution?', answer: 'James Watt', options: ['George Stephenson', 'James Watt', 'Robert Fulton', 'Eli Whitney'] },
      { id: 'automobile', emoji: '🚗', question: 'Who built the first modern gasoline-powered automobile in 1886?', answer: 'Karl Benz', options: ['Henry Ford', 'Karl Benz', 'Gottlieb Daimler', 'Ferdinand Porsche'] },
      { id: 'radio', emoji: '📻', question: 'Who developed long-distance radio communication and wireless telegraphy?', answer: 'Guglielmo Marconi', options: ['Nikola Tesla', 'Samuel Morse', 'Guglielmo Marconi', 'Heinrich Hertz'] },
      { id: 'www', emoji: '🌐', question: 'Who invented the World Wide Web (WWW) in 1989 while working at CERN?', answer: 'Tim Berners-Lee', options: ['Tim Berners-Lee', 'Vint Cerf', 'Marc Andreessen', 'Bill Gates'] },
      { id: 'wheel', emoji: '🛞', question: 'Which ancient civilization is credited with inventing the wheel for pottery and carts?', answer: 'Ancient Mesopotamia', options: ['Ancient Egypt', 'Ancient Mesopotamia', 'Ancient Greece', 'Ancient Rome'] },
      { id: 'battery', emoji: '🔋', question: 'Who created the first electric battery (the Voltaic Pile) in 1800?', answer: 'Alessandro Volta', options: ['Luigi Galvani', 'Michael Faraday', 'Alessandro Volta', 'Nikola Tesla'] },
      { id: 'xray', emoji: '🩵', question: 'Who discovered X-rays in 1895 and won the first Nobel Prize in Physics?', answer: 'Wilhelm Röntgen', options: ['Wilhelm Röntgen', 'Marie Curie', 'Henri Becquerel', 'Ernest Rutherford'] },
      { id: 'microscope', emoji: '🔬', question: 'Who built powerful microscopes to discover bacteria and microscopic life?', answer: 'Antonie van Leeuwenhoek', options: ['Robert Hooke', 'Antonie van Leeuwenhoek', 'Louis Pasteur', 'Gregor Mendel'] },
      { id: 'dynamite', emoji: '🧨', question: 'Who invented dynamite and created the Nobel Prizes in his will?', answer: 'Alfred Nobel', options: ['Dmitri Mendeleev', 'Antoine Lavoisier', 'Alfred Nobel', 'Louis Nobel'] },
      { id: 'clock', emoji: '⏰', question: 'Who invented the pendulum clock in 1656 for accurate timekeeping?', answer: 'Christiaan Huygens', options: ['Galileo Galilei', 'Christiaan Huygens', 'Robert Hooke', 'Isaac Newton'] },
      { id: 'thermometer', emoji: '🌡️', question: 'Who invented the mercury-in-glass thermometer and scale named after him?', answer: 'Daniel Fahrenheit', options: ['Anders Celsius', 'Lord Kelvin', 'Galileo Galilei', 'Daniel Fahrenheit'] }
    ]
  }
};
